In [2]:
import numpy as np
import matplotlib.pyplot as plt

# Function to generate random samples from N(µ, Σ)
def generate_samples(mean, cov, num_samples=100):
    samples = np.random.multivariate_normal(mean, cov, num_samples)
    return samples

# Test1
mean = [0, 0, 0]  # 3-dimensional mean vector
cov = [[1, 0.5, 0.3], [0.5, 1, 0.2], [0.3, 0.2, 1]]  # Covariance matrix
num_samples = 10

samples_1 = generate_samples(mean, cov, num_samples)
print("Random samples:\n",samples_1)

# Test
mean = [0, 0]
cov = [[1, 0], [0, 1]]
samples_2 = generate_samples(mean, cov, 5)
print("Random samples:\n", samples_2)

Matplotlib is building the font cache; this may take a moment.


Random samples:
 [[ 9.33372694e-02  1.60757775e+00  3.27983859e-01]
 [-1.97738974e+00 -2.93488031e-01  3.14317964e-01]
 [ 1.38989697e+00  6.68189863e-01 -1.83088708e-01]
 [-5.46809555e-01 -1.14341548e+00 -8.80944731e-01]
 [-2.53276709e-02  4.05720481e-01 -1.82170801e-01]
 [ 7.27449638e-01  2.05875417e-01  4.37875587e-01]
 [-2.16023516e+00 -1.43710220e+00 -7.52390990e-01]
 [ 2.51915685e-01  3.43577969e-01  1.10116024e+00]
 [ 1.14704003e+00  5.56338464e-03 -7.67512056e-01]
 [-2.09840590e-04  1.02098234e+00 -5.06010283e-02]]
Random samples:
 [[ 0.92210643 -0.86243178]
 [-0.73942702 -1.1746    ]
 [ 0.23609491 -0.86519767]
 [ 1.39071334  0.26442668]
 [ 0.48574086 -0.57154715]]


In [3]:
def discriminant_function(x, mean, cov, prior_prob):
    cov_inv = np.linalg.inv(cov)
    cov_det = np.linalg.det(cov)
    d = len(x)
    
    term1 = -0.5 * np.log(cov_det)
    term2 = -0.5 * np.dot(np.dot((x - mean).T, cov_inv), (x - mean))
    term3 = np.log(prior_prob)
    term4 = -0.5 * d * np.log(2 * np.pi)
    
    return term1 + term2 + term3 + term4

# taking test data reference from second problem 
data1 = [[-5.01, -8.12, -3.68],
         [-5.43, -3.48, -3.54],
         [ 1.08, -5.52,  1.66],
         [ 0.86, -3.78, -4.11],
         [-2.67,  0.63,  7.39],
         [ 4.94,  3.29,  2.08],
         [-2.51,  2.09, -2.59],
         [-2.25, -2.13, -6.94],
         [ 5.56,  2.86, -2.26],
         [ 1.03, -3.33,  4.33]]

data1 = np.array(data1)

# Test
mean = np.array([0, 0, 0])
cov = np.cov(data1.T)  # Covariance matrix 
prior_prob = 0.5 

discriminant_values = []
for x in data1:
    g_x = discriminant_function(x, mean, cov, prior_prob)
    discriminant_values.append(g_x)

for i, val in enumerate(discriminant_values):
    print(f"Discriminant value for data point {i + 1}: {val}")

Discriminant value for data point 1: -9.742992723074721
Discriminant value for data point 2: -8.550076134856967
Discriminant value for data point 3: -9.371369114814723
Discriminant value for data point 4: -8.661507416356068
Discriminant value for data point 5: -9.535682282257529
Discriminant value for data point 6: -8.288339188427187
Discriminant value for data point 7: -8.35257304860075
Discriminant value for data point 8: -8.661812066640318
Discriminant value for data point 9: -8.889455292376104
Discriminant value for data point 10: -8.76042133294347


In [4]:
def euclidean_distance(x1, x2):
    dist = np.linalg.norm(x1 - x2)
    return dist

# Test
x1 = np.array([1, 2, 3])
x2 = np.array([4, 5, 6])

euclid_dist = euclidean_distance(x1, x2)
print(f"Euclidean distance: {euclid_dist}")

Euclidean distance: 5.196152422706632


In [5]:
def mahalanobis_distance(x, mean, cov):
    cov_inv = np.linalg.inv(cov)
    diff = x - mean
    dist = np.sqrt(np.dot(np.dot(diff.T, cov_inv), diff))
    return dist

# Test data
x = np.array([1, 2, 3])

mahal_dist = mahalanobis_distance(x, mean, cov)
print(f"Mahalanobis distance: {mahal_dist}")

Mahalanobis distance: 0.7806737036126006


In [6]:
data1 = np.array([[-5.01, -8.12, -3.68],
                  [-5.43, -3.48, -3.54],
                  [ 1.08, -5.52,  1.66],
                  [ 0.86, -3.78, -4.11],
                  [-2.67,  0.63,  7.39],
                  [ 4.94,  3.29,  2.08],
                  [-2.51,  2.09, -2.59],
                  [-2.25, -2.13, -6.94],
                  [ 5.56,  2.86, -2.26],
                  [ 1.03, -3.33,  4.33]])

data2 = np.array([[-0.91, -0.18, -0.05],
                  [ 1.30, -2.06, -3.53],
                  [-7.75, -4.54, -0.95],
                  [-5.47,  0.50,  3.92],
                  [ 6.14,  5.72, -4.85],
                  [ 3.60,  1.26,  4.36],
                  [ 5.37, -4.63, -3.65],
                  [ 7.18,  1.46, -6.66],
                  [-7.39,  1.17,  6.30],
                  [-7.50, -6.32, -0.31]])

data3 = np.array([[ 5.35,  2.26,  8.13],
                  [ 5.12,  3.22, -2.66],
                  [-1.34, -5.31, -9.87],
                  [ 4.48,  3.42,  5.19],
                  [ 7.11,  2.39,  9.21],
                  [ 7.17,  4.33, -0.98],
                  [ 5.75,  3.97,  6.65],
                  [ 0.77,  0.27,  2.41],
                  [ 0.90, -0.43, -8.71],
                  [ 3.52, -0.36,  6.43]])

In [7]:
# Prior probabilities (P(w1) = P(w3) = 1/2, P(w2) = 0)
prior_w1 = 0.5
prior_w2 = 0
prior_w3 = 0.5

In [8]:
# Use only the x1 feature
x1_data1 = data1[:, 0]
x1_data2 = data2[:, 0]
x1_data3 = data3[:, 0]

# Compute the mean and variance 
mean1 = np.mean(x1_data1)
mean2 = np.mean(x1_data2)
mean3 = np.mean(x1_data3)

var1 = np.var(x1_data1)
var2 = np.var(x1_data2)
var3 = np.var(x1_data3)
cov1 = np.array([[var1]])
cov3 = np.array([[var3]])

# Classify data points in data1 using the discriminant function
for x in x1_data1:
    g1 = discriminant_function(np.array([x]), np.array([mean1]), cov1, prior_w1)
    g3 = discriminant_function(np.array([x]), np.array([mean3]), cov3, prior_w3)
    if g1 > g3:
        print(f"Point {x} is classified as Class 1")
    else:
        print(f"Point {x} is classified as Class 3")

Point -5.01 is classified as Class 1
Point -5.43 is classified as Class 1
Point 1.08 is classified as Class 1
Point 0.86 is classified as Class 1
Point -2.67 is classified as Class 1
Point 4.94 is classified as Class 3
Point -2.51 is classified as Class 1
Point -2.25 is classified as Class 1
Point 5.56 is classified as Class 3
Point 1.03 is classified as Class 1


In [9]:
# Combine data1 and data3
x1_combined = np.concatenate([x1_data1, x1_data3])
true_labels = np.concatenate([np.ones(len(x1_data1)), np.full(len(x1_data3), 3)])  # Class 1 and Class 3

# Store predicted labels
predicted_labels = []

# Classify data points
for x in x1_combined:
    g1 = discriminant_function(np.array([x]), np.array([mean1]), cov1, prior_w1)
    g3 = discriminant_function(np.array([x]), np.array([mean3]), cov3, prior_w3)
    if g1 > g3:
        predicted_labels.append(1)  # Class 1
    else:
        predicted_labels.append(3)  # Class 3

# Calculate empirical training error
predicted_labels = np.array(predicted_labels)
errors = np.sum(predicted_labels != true_labels)

empirical_error = (errors / len(true_labels)) * 100
print(f"Empirical training error is {empirical_error:.2f}%")

Empirical training error is 25.00%


In [10]:
def bhattacharyya_bound(mean1, mean3, cov1, cov3):
    # Calculate the average covariance matrix
    cov_avg = (cov1 + cov3) / 2
    diff_mean = mean3 - mean1
    
    # First term
    cov_avg_inv = np.linalg.inv(cov_avg)
    term1 = 0.125 * np.dot(np.dot(diff_mean.T, cov_avg_inv), diff_mean)
    
    # Second term
    det_cov_avg = np.linalg.det(cov_avg)
    det_cov1 = np.linalg.det(cov1)
    det_cov3 = np.linalg.det(cov3)
    term2 = 0.5 * np.log(det_cov_avg / np.sqrt(det_cov1 * det_cov3))
    
    # Bhattacharyya coefficient
    B = term1 + term2
    error_bound = np.exp(-B)
    return B, error_bound

# Compute Bhattacharyya bound for x1 (one feature)
bhatt_B_1d, bhatt_bound_1d = bhattacharyya_bound(np.array([mean1]), np.array([mean3]), cov1, cov3)
print(f"Bhattacharyya bound for one feature: {bhatt_bound_1d:.4f}")

Bhattacharyya bound for one feature: 0.7808


In [11]:
# Use x1 and x2 features
x12_data1 = data1[:, :2]
x12_data3 = data3[:, :2]

mean1_2d = np.mean(x12_data1, axis=0)
mean3_2d = np.mean(x12_data3, axis=0)

cov1_2d = np.cov(x12_data1, rowvar=False)
cov3_2d = np.cov(x12_data3, rowvar=False)

# Combine the data and true labels for classification
x12_combined = np.concatenate([x12_data1, x12_data3])
true_labels_2d = np.concatenate([np.ones(len(x12_data1)), np.full(len(x12_data3), 3)])

predicted_labels_2d = []
for x in x12_combined:
    g1 = discriminant_function(x, mean1_2d, cov1_2d, prior_w1)
    g3 = discriminant_function(x, mean3_2d, cov3_2d, prior_w3)
    if g1 > g3:
        predicted_labels_2d.append(1)
    else:
        predicted_labels_2d.append(3)

# Calculate empirical training error for 2D
predicted_labels_2d = np.array(predicted_labels_2d)
errors_2d = np.sum(predicted_labels_2d != true_labels_2d)
empirical_error_2d = (errors_2d / len(true_labels_2d)) * 100
print(f"Empirical training error for 2 features: {empirical_error_2d:.2f}%")


Empirical training error for 2 features: 20.00%


In [12]:
def bhattacharyya_bound(mean1, mean3, cov1, cov3):
    cov_avg = (cov1 + cov3) / 2
    diff_mean = mean3 - mean1
    
    # First term
    cov_avg_inv = np.linalg.inv(cov_avg)
    term1 = 0.125 * np.dot(np.dot(diff_mean.T, cov_avg_inv), diff_mean)
    
    # Second term
    det_cov_avg = np.linalg.det(cov_avg)
    det_cov1 = np.linalg.det(cov1)
    det_cov3 = np.linalg.det(cov3)
    term2 = 0.5 * np.log(det_cov_avg / np.sqrt(det_cov1 * det_cov3))
    
    # Bhattacharyya coefficient
    B = term1 + term2
    error_bound = np.exp(-B)
    return B, error_bound

# Compute Bhattacharyya bound for the 3 features case
bhatt_B_2d, bhatt_bound_2d = bhattacharyya_bound(mean1_2d, mean3_2d, cov1_2d, cov3_2d)
# print(f"Bhattacharyya coefficient (B) for 2 features : {bhatt_B_2d:.4f}")
print(f"Bhattacharyya bound for 2 features: {bhatt_bound_2d:.4f}")


Bhattacharyya bound for 2 features: 0.6584


In [13]:
# Use x1, x2, and x3 features (all features)
x123_data1 = data1  
x123_data3 = data3 

mean1_3d = np.mean(x123_data1, axis=0)
mean3_3d = np.mean(x123_data3, axis=0)

cov1_3d = np.cov(x123_data1, rowvar=False)
cov3_3d = np.cov(x123_data3, rowvar=False)

x123_combined = np.concatenate([x123_data1, x123_data3])
true_labels_3d = np.concatenate([np.ones(len(x123_data1)), np.full(len(x123_data3), 3)])

predicted_labels_3d = []
for x in x123_combined:
    g1 = discriminant_function(x, mean1_3d, cov1_3d, prior_w1)
    g3 = discriminant_function(x, mean3_3d, cov3_3d, prior_w3)
    if g1 > g3:
        predicted_labels_3d.append(1)
    else:
        predicted_labels_3d.append(3)

# Calculate empirical training error for 3D
predicted_labels_3d = np.array(predicted_labels_3d)
errors_3d = np.sum(predicted_labels_3d != true_labels_3d)
empirical_error_3d = (errors_3d / len(true_labels_3d)) * 100
print(f"Empirical training error for 3 features: {empirical_error_3d:.2f}%")

Empirical training error for 3 features: 15.00%


In [14]:
def bhattacharyya_bound(mean1, mean3, cov1, cov3):
    cov_avg = (cov1 + cov3) / 2
    diff_mean = mean3 - mean1
    
    # First term
    cov_avg_inv = np.linalg.inv(cov_avg)
    term1 = 0.125 * np.dot(np.dot(diff_mean.T, cov_avg_inv), diff_mean)
    
    # Second term
    det_cov_avg = np.linalg.det(cov_avg)
    det_cov1 = np.linalg.det(cov1)
    det_cov3 = np.linalg.det(cov3)
    term2 = 0.5 * np.log(det_cov_avg / np.sqrt(det_cov1 * det_cov3))
    
    # Bhattacharyya coefficient
    B = term1 + term2
    error_bound = np.exp(-B)
    return B, error_bound

# Compute Bhattacharyya bound for the 3 features case
bhatt_B_3d, bhatt_bound_3d = bhattacharyya_bound(mean1_3d, mean3_3d, cov1_3d, cov3_3d)
# print(f"Bhattacharyya coefficient (B) for 3 features : {bhatt_B_3d:.4f}")
print(f"Bhattacharyya bound for 3 features: {bhatt_bound_3d:.4f}")


Bhattacharyya bound for 3 features: 0.5987
